name: Build

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'CMakeLists.txt'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'CMakeLists.txt'

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
    - uses: actions/checkout@v3

    - name: Linux requirements
      run: sudo apt-get install libxi-dev libgl1-mesa-dev libglu1-mesa-dev mesa-common-dev libxrandr-dev libxxf86vm-dev

    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh -disableMetrics

    - name: Prep Cmake
      run: |
        vcpkg install
        mkdir build
        cd build
        cmake ../ -DCMAKE_TOOLCHAIN_FILE="vcpkg/scripts/buildsystems/vcpkg.cmake"

    - name: Build
      run: cmake --build build/
